import {EStatus} from "@/components/common/primitives/Indicator";
import {TExhauster} from "@/components/common/primitives/CustomCard/CustomCard";


export const exhausters: TExhauster[] = [
    {
        status: EStatus.ERROR,
        exhausterNumber: 4,
        rotors: [
            {
                rotorNumber: 1,
                lastReplacementDate: "01.04.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 11,
                oilLevelStatus: EStatus.WARNING,
                vibration: 9,
                vibrationStatus: EStatus.NORMAL,
                temperature: 7,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 2,
                lastReplacementDate: "03.02.2023",
                forecastReplacementDate: 17,
                forecastDate: 61,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 21,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 91,
                vibrationStatus: EStatus.NORMAL,
                temperature: 78,
                temperatureStatus: EStatus.WARNING,
            }, {
                rotorNumber: 3,
                lastReplacementDate: "24.03.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 51,
                oilLevelStatus: EStatus.WARNING,
                vibration: 15,
                vibrationStatus: EStatus.ERROR,
                temperature: 57,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 4,
                lastReplacementDate: "20.01.2023",
                forecastReplacementDate: 120,
                forecastDate: 14,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 10,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 99,
                vibrationStatus: EStatus.NORMAL,
                temperature: 16,
                temperatureStatus: EStatus.ERROR,
            },
        ]
    },
    {
        status: EStatus.WARNING,
        exhausterNumber: 5,
        rotors: [
            {
                rotorNumber: 1,
                lastReplacementDate: "01.04.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 11,
                oilLevelStatus: EStatus.WARNING,
                vibration: 9,
                vibrationStatus: EStatus.NORMAL,
                temperature: 7,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 2,
                lastReplacementDate: "03.02.2023",
                forecastReplacementDate: 17,
                forecastDate: 61,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 21,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 91,
                vibrationStatus: EStatus.NORMAL,
                temperature: 78,
                temperatureStatus: EStatus.WARNING,
            }, {
                rotorNumber: 3,
                lastReplacementDate: "24.03.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 51,
                oilLevelStatus: EStatus.WARNING,
                vibration: 15,
                vibrationStatus: EStatus.ERROR,
                temperature: 57,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 4,
                lastReplacementDate: "20.01.2023",
                forecastReplacementDate: 120,
                forecastDate: 14,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 10,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 99,
                vibrationStatus: EStatus.NORMAL,
                temperature: 16,
                temperatureStatus: EStatus.ERROR,
            },
        ]
    },
    {
        status: EStatus.NORMAL,
        exhausterNumber: 6,
        rotors: [
            {
                rotorNumber: 1,
                lastReplacementDate: "01.04.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 11,
                oilLevelStatus: EStatus.WARNING,
                vibration: 9,
                vibrationStatus: EStatus.NORMAL,
                temperature: 7,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 2,
                lastReplacementDate: "03.02.2023",
                forecastReplacementDate: 17,
                forecastDate: 61,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 21,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 91,
                vibrationStatus: EStatus.NORMAL,
                temperature: 78,
                temperatureStatus: EStatus.WARNING,
            }, {
                rotorNumber: 3,
                lastReplacementDate: "24.03.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 51,
                oilLevelStatus: EStatus.WARNING,
                vibration: 15,
                vibrationStatus: EStatus.ERROR,
                temperature: 57,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 4,
                lastReplacementDate: "20.01.2023",
                forecastReplacementDate: 120,
                forecastDate: 14,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 10,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 99,
                vibrationStatus: EStatus.NORMAL,
                temperature: 16,
                temperatureStatus: EStatus.ERROR,
            },
        ]
    },
    {
        status: EStatus.ERROR,
        exhausterNumber: 7,
        rotors: [
            {
                rotorNumber: 1,
                lastReplacementDate: "01.04.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 11,
                oilLevelStatus: EStatus.WARNING,
                vibration: 9,
                vibrationStatus: EStatus.NORMAL,
                temperature: 7,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 2,
                lastReplacementDate: "03.02.2023",
                forecastReplacementDate: 17,
                forecastDate: 61,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 21,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 91,
                vibrationStatus: EStatus.NORMAL,
                temperature: 78,
                temperatureStatus: EStatus.WARNING,
            }, {
                rotorNumber: 3,
                lastReplacementDate: "24.03.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 51,
                oilLevelStatus: EStatus.WARNING,
                vibration: 15,
                vibrationStatus: EStatus.ERROR,
                temperature: 57,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 4,
                lastReplacementDate: "20.01.2023",
                forecastReplacementDate: 120,
                forecastDate: 14,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 10,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 99,
                vibrationStatus: EStatus.NORMAL,
                temperature: 16,
                temperatureStatus: EStatus.ERROR,
            },
        ]
    },
    {
        status: EStatus.WARNING,
        exhausterNumber: 8,
        rotors: [
            {
                rotorNumber: 1,
                lastReplacementDate: "01.04.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 11,
                oilLevelStatus: EStatus.WARNING,
                vibration: 9,
                vibrationStatus: EStatus.NORMAL,
                temperature: 7,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 2,
                lastReplacementDate: "03.02.2023",
                forecastReplacementDate: 17,
                forecastDate: 61,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 21,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 91,
                vibrationStatus: EStatus.NORMAL,
                temperature: 78,
                temperatureStatus: EStatus.WARNING,
            }, {
                rotorNumber: 3,
                lastReplacementDate: "24.03.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 51,
                oilLevelStatus: EStatus.WARNING,
                vibration: 15,
                vibrationStatus: EStatus.ERROR,
                temperature: 57,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 4,
                lastReplacementDate: "20.01.2023",
                forecastReplacementDate: 120,
                forecastDate: 14,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 10,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 99,
                vibrationStatus: EStatus.NORMAL,
                temperature: 16,
                temperatureStatus: EStatus.ERROR,
            },
        ]
    },
    {
        status: EStatus.ERROR,
        exhausterNumber: 9,
        rotors: [
            {
                rotorNumber: 1,
                lastReplacementDate: "01.04.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 11,
                oilLevelStatus: EStatus.WARNING,
                vibration: 9,
                vibrationStatus: EStatus.NORMAL,
                temperature: 7,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 2,
                lastReplacementDate: "03.02.2023",
                forecastReplacementDate: 17,
                forecastDate: 61,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 21,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 91,
                vibrationStatus: EStatus.NORMAL,
                temperature: 78,
                temperatureStatus: EStatus.WARNING,
            }, {
                rotorNumber: 3,
                lastReplacementDate: "24.03.2023",
                forecastReplacementDate: 9,
                forecastDate: 11,
                forecastReplacementStatus: EStatus.WARNING,
                oilLevel: 51,
                oilLevelStatus: EStatus.WARNING,
                vibration: 15,
                vibrationStatus: EStatus.ERROR,
                temperature: 57,
                temperatureStatus: EStatus.ERROR,
            }, {
                rotorNumber: 4,
                lastReplacementDate: "20.01.2023",
                forecastReplacementDate: 120,
                forecastDate: 14,
                forecastReplacementStatus: EStatus.NORMAL,
                oilLevel: 10,
                oilLevelStatus: EStatus.NORMAL,
                vibration: 99,
                vibrationStatus: EStatus.NORMAL,
                temperature: 16,
                temperatureStatus: EStatus.ERROR,
            },
        ]
    },

]
