import {EStatus} from "@/components/common/primitives/Indicator";
import {TExhauster} from "@/components/common/primitives/ExhausterCard";

export const exhausters: TExhauster[] = [
    {
        status: EStatus.ERROR,
        exhausterNumber: 4,
        rotorNumber: 5,
        lastReplacementDate: "20.09.2023",
        forecastReplacementDate: 9,
        forecastDate: 11,
        forecastReplacementStatus: EStatus.WARNING,
        oilLevel: 43,
        oilLevelStatus: EStatus.ERROR,
        vibration: 72,
        vibrationStatus: EStatus.NORMAL,
        temperature: 16,
        temperatureStatus: EStatus.ERROR,
    },
    {
        status: EStatus.NORMAL,
        exhausterNumber: 5,
        rotorNumber: 9,
        lastReplacementDate: "11.06.2023",
        forecastReplacementDate: 10,
        forecastDate: 10,
        forecastReplacementStatus: EStatus.ERROR,
        oilLevel: 88,
        oilLevelStatus: EStatus.WARNING,
        vibration: 32,
        vibrationStatus: EStatus.ERROR,
        temperature: 46,
        temperatureStatus: EStatus.ERROR,
    },    {
        status: EStatus.NORMAL,
        exhausterNumber: 6,
        rotorNumber: 11,
        lastReplacementDate: "08.04.2023",
        forecastReplacementDate: 10,
        forecastDate: 10,
        forecastReplacementStatus: EStatus.ERROR,
        oilLevel: 76,
        oilLevelStatus: EStatus.WARNING,
        vibration: 14,
        vibrationStatus: EStatus.ERROR,
        temperature: 17,
        temperatureStatus: EStatus.ERROR,
    },    {
        status: EStatus.WARNING,
        exhausterNumber: 7,
        rotorNumber: 4,
        lastReplacementDate: "25.10.2023",
        forecastReplacementDate: 10,
        forecastDate: 10,
        forecastReplacementStatus: EStatus.WARNING,
        oilLevel: 17,
        oilLevelStatus: EStatus.NORMAL,
        vibration: 18,
        vibrationStatus: EStatus.ERROR,
        temperature: 19,
        temperatureStatus: EStatus.WARNING,
    },    {
        status: EStatus.ERROR,
        exhausterNumber: 8,
        rotorNumber: 13,
        lastReplacementDate: "02.11.2023",
        forecastReplacementDate: 15,
        forecastDate: 2,
        forecastReplacementStatus: EStatus.ERROR,
        oilLevel: 54,
        oilLevelStatus: EStatus.NORMAL,
        vibration: 45,
        vibrationStatus: EStatus.NORMAL,
        temperature: 69,
        temperatureStatus: EStatus.ERROR,
    }, {
        status: EStatus.WARNING,
        exhausterNumber: 9,
        rotorNumber: 4,
        lastReplacementDate: "15.05.2023",
        forecastReplacementDate: 23,
        forecastDate: 55,
        forecastReplacementStatus: EStatus.ERROR,
        oilLevel: 13,
        oilLevelStatus: EStatus.ERROR,
        vibration: 77,
        vibrationStatus: EStatus.NORMAL,
        temperature: 14,
        temperatureStatus: EStatus.WARNING,
    },

]
